name: Build and Push Docker Image (PySpark Wine)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (without push for testing)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true  # Load image to local docker instead of pushing
          tags: pyspark-wine:test
          platforms: linux/amd64  # Reduce to single platform for easier debugging

      - name: Test Docker image
        run: |
          docker images
          docker run --rm pyspark-wine:test echo "Docker image built successfully"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyspark-wine:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pyspark-wine:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pyspark-wine:cache
          cache-to: type=inline,mode=max
