name: Build and Push Docker Image

# Trigger the workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Step 2: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Step 3: Log in to Docker Hub using GitHub secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use secret for Docker username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Use secret for Docker password
    
    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/pyspark-wine:${{ github.sha }} .
    
    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/pyspark-wine:${{ github.sha }}

    # Step 6: Optionally, push the `latest` tag
    - name: Push Docker image with latest tag
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/pyspark-wine:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/pyspark-wine:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/pyspark-wine:latest
